import { Activity, Database, FileClock, Languages, Moon, Network, Power, Save, Sun, TerminalSquare } from "lucide-react";
import { useState } from "react";
import { api } from "../api";
import type { Config } from "../types";
import type { Language, MessageKey } from "../i18n";

export type Theme = "light" | "dark" | "system";
type RefreshResource = "status" | "localAccess" | "config" | "providers" | "clients" | "logs" | "usage";
type Translator = (key: MessageKey) => string;

function SectionHeader({ title }: { title: string }) { return <div className="section-header"><div><h2>{title}</h2></div></div>; }

export function SettingsPage({ config, language, theme, setLanguage, setTheme, t, run }: { config: Config; language: Language; theme: Theme; setLanguage: (v: Language) => void; setTheme: (v: Theme) => void; t: Translator; run: (op: () => Promise<unknown>, message?: string, resources?: RefreshResource[]) => Promise<void> }) {
  const limits = config.limits || { global: 0, per_client: 0, per_provider: 0, stream_idle_seconds: 300, request_body_bytes: 0, request_header_bytes: 0, client_rate_per_minute: 0 };
  const [host, setHost] = useState(config.listen.host || "127.0.0.1"); const [port, setPort] = useState(config.listen.port); const [logDir, setLogDir] = useState(config.logging.dir); const [retentionDays, setRetentionDays] = useState(config.logging.retention_days || 0); const [quotaBytes, setQuotaBytes] = useState(config.logging.quota_bytes || 0);
  const [globalLimit, setGlobalLimit] = useState(limits.global); const [clientLimit, setClientLimit] = useState(limits.per_client); const [providerLimit, setProviderLimit] = useState(limits.per_provider);
  const [streamIdleSeconds, setStreamIdleSeconds] = useState(limits.stream_idle_seconds);
  const [requestBodyBytes, setRequestBodyBytes] = useState(limits.request_body_bytes); const [requestHeaderBytes, setRequestHeaderBytes] = useState(limits.request_header_bytes); const [clientRatePerMinute, setClientRatePerMinute] = useState(limits.client_rate_per_minute);
  const save = () => run(() => api.updateConfig({ ...config, limits: { global: globalLimit, per_client: clientLimit, per_provider: providerLimit, stream_idle_seconds: streamIdleSeconds, request_body_bytes: requestBodyBytes, request_header_bytes: requestHeaderBytes, client_rate_per_minute: clientRatePerMinute }, listen: { host, port }, logging: { ...config.logging, dir: logDir, retention_days: retentionDays, quota_bytes: quotaBytes }, ui: { ...config.ui, language } }), t("success"), ["config", "status", "logs"]);
  const dirty = host !== (config.listen.host || "127.0.0.1") || port !== config.listen.port || logDir !== config.logging.dir || retentionDays !== (config.logging.retention_days || 0) || quotaBytes !== (config.logging.quota_bytes || 0) || language !== config.ui.language || globalLimit !== limits.global || clientLimit !== limits.per_client || providerLimit !== limits.per_provider || streamIdleSeconds !== limits.stream_idle_seconds || requestBodyBytes !== limits.request_body_bytes || requestHeaderBytes !== limits.request_header_bytes || clientRatePerMinute !== limits.client_rate_per_minute;
  const invalid = port < 1024 || port > 65535 || !logDir.trim() || retentionDays < 0 || retentionDays > 3650 || quotaBytes < 0 || quotaBytes > 1099511627776 || [globalLimit, clientLimit, providerLimit].some((value) => value < 0 || value > 1024) || streamIdleSeconds < 1 || streamIdleSeconds > 86400 || requestBodyBytes < 0 || requestBodyBytes > 134217728 || requestHeaderBytes < 0 || requestHeaderBytes > 1048576 || clientRatePerMinute < 0 || clientRatePerMinute > 100000;
  return <section><SectionHeader title={t("settings")} />
    <div className="settings-group"><h3>{t("interfaceSettings")}</h3><div className="settings-list interface-list"><div className="setting-row"><div><Languages size={17} /><span><strong>{t("language")}</strong><small>UI / config.yaml</small></span></div><select value={language} onChange={(e) => setLanguage(e.target.value as Language)}><option value="zh-CN">简体中文</option><option value="en-US">English</option></select></div><div className="setting-row"><div><Sun size={17} /><span><strong>{t("theme")}</strong><small>{t("localPreference")}</small></span></div><div className="segmented">{(["light", "dark", "system"] as Theme[]).map((value) => <button className={theme === value ? "selected" : ""} key={value} onClick={() => setTheme(value)}>{value === "dark" && <Moon size={14} />}{value === "light" && <Sun size={14} />}{value === "system" && <TerminalSquare size={14} />}{t(value)}</button>)}</div></div></div></div>
    <div className="settings-group"><h3>{t("gatewaySettings")}</h3><div className="settings-list gateway-list"><div className="setting-row"><div><Power size={17} /><span><strong>{t("autostart")}</strong><small>{t("currentUserSession")}</small></span></div><label className="switch"><input type="checkbox" aria-label={t("autostart")} checked={config.autostart.enabled} onChange={(e) => void run(() => api.setAutostart(e.target.checked), t("success"), ["status"])} /><span /></label></div><div className="setting-row"><div><Network size={17} /><span><strong>{t("listenHost")}</strong><small>{t("listenHostDescription")}</small></span></div><select value={host} onChange={(e) => setHost(e.target.value)}><option value="127.0.0.1">127.0.0.1</option><option value="0.0.0.0">0.0.0.0</option></select></div><div className="setting-row"><div><Network size={17} /><span><strong>{t("port")}</strong><small>{t("listenPortDescription")}</small></span></div><input className="short-input mono" type="number" min="1024" max="65535" value={port} onChange={(e) => setPort(Number(e.target.value))} /></div></div></div>
    <div className="settings-group"><h3>{t("concurrencyLimits")}</h3><div className="settings-list limits-list"><div className="setting-row"><div><Activity size={17} /><span><strong>{t("globalConcurrency")}</strong><small>{t("concurrencyLimitHint")}</small></span></div><input className="short-input mono" type="number" min="0" max="1024" value={globalLimit} onChange={(e) => setGlobalLimit(Number(e.target.value))} aria-label={t("globalConcurrency")} /></div><div className="setting-row"><div><Activity size={17} /><span><strong>{t("clientConcurrency")}</strong><small>{t("concurrencyLimitHint")}</small></span></div><input className="short-input mono" type="number" min="0" max="1024" value={clientLimit} onChange={(e) => setClientLimit(Number(e.target.value))} aria-label={t("clientConcurrency")} /></div><div className="setting-row"><div><Activity size={17} /><span><strong>{t("providerConcurrency")}</strong><small>{t("concurrencyLimitHint")}</small></span></div><input className="short-input mono" type="number" min="0" max="1024" value={providerLimit} onChange={(e) => setProviderLimit(Number(e.target.value))} aria-label={t("providerConcurrency")} /></div><div className="setting-row"><div><Activity size={17} /><span><strong>{t("streamIdleTimeout")}</strong><small>{t("streamIdleTimeoutHint")}</small></span></div><input className="short-input mono" type="number" min="1" max="86400" value={streamIdleSeconds} onChange={(e) => setStreamIdleSeconds(Number(e.target.value))} aria-label={t("streamIdleTimeout")} /></div><div className="setting-row"><div><Database size={17} /><span><strong>{t("requestBodyLimit")}</strong><small>{t("requestBodyLimitHint")}</small></span></div><input className="short-input mono" type="number" min="0" max="134217728" value={requestBodyBytes} onChange={(e) => setRequestBodyBytes(Number(e.target.value))} aria-label={t("requestBodyLimit")} /></div><div className="setting-row"><div><Network size={17} /><span><strong>{t("requestHeaderLimit")}</strong><small>{t("requestHeaderLimitHint")}</small></span></div><input className="short-input mono" type="number" min="0" max="1048576" value={requestHeaderBytes} onChange={(e) => setRequestHeaderBytes(Number(e.target.value))} aria-label={t("requestHeaderLimit")} /></div><div className="setting-row"><div><Activity size={17} /><span><strong>{t("clientRateLimit")}</strong><small>{t("clientRateLimitHint")}</small></span></div><input className="short-input mono" type="number" min="0" max="100000" value={clientRatePerMinute} onChange={(e) => setClientRatePerMinute(Number(e.target.value))} aria-label={t("clientRateLimit")} /></div></div></div>
    <div className="settings-group"><h3>{t("logSettings")}</h3><div className="settings-list logging-list"><div className="setting-row"><div><FileClock size={17} /><span><strong>{t("logging")}</strong><small>{t("loggingDescription")}</small></span></div><label className="switch"><input type="checkbox" aria-label={t("logging")} checked={config.logging.enabled} onChange={(e) => void run(() => api.setLogging(e.target.checked), t("success"), ["config", "status", "logs"])} /><span /></label></div><div className="setting-row"><div><FileClock size={17} /><span><strong>{t("bodyLogging")}</strong><small>{t("bodyLoggingDescription")}</small></span></div><label className="switch"><input type="checkbox" aria-label={t("bodyLogging")} checked={config.logging.enabled && config.logging.body !== false} disabled={!config.logging.enabled} onChange={(e) => void run(() => api.setLoggingBody(e.target.checked), t("success"), ["config", "status", "logs"])} /><span /></label></div><div className="setting-row log-directory-row"><div><FileClock size={17} /><span><strong>{t("logDir")}</strong><small>{t("relativeDataRoot")}</small></span></div><input value={logDir} onChange={(e) => setLogDir(e.target.value)} /></div><div className="setting-row"><div><FileClock size={17} /><span><strong>{t("logRetention")}</strong><small>{t("logRetentionHint")}</small></span></div><input className="short-input mono" type="number" min="0" max="3650" value={retentionDays} onChange={(e) => setRetentionDays(Number(e.target.value))} aria-label={t("logRetention")} /></div><div className="setting-row"><div><Database size={17} /><span><strong>{t("logQuota")}</strong><small>{t("logQuotaHint")}</small></span></div><input className="short-input mono" type="number" min="0" max="1099511627776" value={quotaBytes} onChange={(e) => setQuotaBytes(Number(e.target.value))} aria-label={t("logQuota")} /></div></div></div>
    {dirty && <div className="settings-footer"><span className="muted">{t("unsavedChanges")}</span><button className="primary" onClick={() => void save()} disabled={invalid}><Save size={16} />{t("saveSettings")}</button></div>}
  </section>;
}
