package codex

import (
	"fmt"

	"ai-gateway/internal/point/clientcatalog"
	"ai-gateway/internal/point/tomledit"
	"github.com/pelletier/go-toml/v2"
)

const PlaceholderEnvironment = "AI_GATEWAY_PLACEHOLDER_KEY"
const PlaceholderValue = "ai-gateway-local"

// providerID is the [model_providers.<id>] table the gateway owns, and the
// value of the root model_provider key (docs/v1-scheme.md §12.3).
const providerID = "ai-gateway"

// ProviderDisplayName is the default [model_providers.ai-gateway].name.
// Codex only treats a provider as OpenAI (and therefore uses remote
// compaction via POST /responses/compact) when this field is exactly
// "OpenAI" (docs/v1-scheme.md §20, 2026-08-16 evidence).
const ProviderDisplayName = "ai-gateway"
const RemoteCompactionDisplayName = "OpenAI"

func providerDisplayName(settings clientcatalog.Settings) string {
	if settings.RemoteCompaction {
		return RemoteCompactionDisplayName
	}
	return ProviderDisplayName
}

// Transform points Codex at the gateway and writes the root model_catalog_json
// key. The sidecar itself is generated by BuildCatalog and written by the
// point transaction; this function only records the absolute path. Entries
// must clone a native bundled template and keep base_instructions
// (docs/v1-scheme.md §12.3, 2026-08-16 evidence).
//
// Only the model and routing keys the gateway owns are rewritten. Everything
// else in config.toml — comments, key order, quoting style, `[mcp_servers.*]`,
// `[plugins.*]`, `[projects.*]` and the rest of the user's tool configuration —
// keeps its original bytes (§12.1, 2026-08-21 evidence in §20). A shape
// tomledit cannot splice falls back to re-encoding the whole document.
func Transform(original []byte, baseURL string, settings clientcatalog.Settings, catalogPath string) ([]byte, error) {
	if catalogPath == "" {
		return nil, fmt.Errorf("Codex catalog path is required")
	}
	if out, err := transformInPlace(original, baseURL, settings, catalogPath); err == nil {
		return out, nil
	}
	return transformWhole(original, baseURL, settings, catalogPath)
}

func transformInPlace(original []byte, baseURL string, settings clientcatalog.Settings, catalogPath string) ([]byte, error) {
	doc, err := tomledit.Parse(original)
	if err != nil {
		return nil, err
	}
	for _, kv := range rootKeys(settings, catalogPath) {
		if err := doc.SetString([]string{kv.Key}, kv.Value); err != nil {
			return nil, err
		}
	}
	if err := doc.SetStrings([]string{"model_providers", providerID}, providerKeys(baseURL, settings)); err != nil {
		return nil, err
	}
	return doc.Bytes()
}

// transformWhole is the fallback for a config.toml whose gateway keys live in an
// inline table or an array of tables. It re-encodes the document, which keeps
// every unknown field and its semantics but not the original layout (§12.1).
func transformWhole(original []byte, baseURL string, settings clientcatalog.Settings, catalogPath string) ([]byte, error) {
	doc, err := parse(original)
	if err != nil {
		return nil, err
	}
	providers, err := object(doc, "model_providers")
	if err != nil {
		return nil, err
	}
	for _, kv := range rootKeys(settings, catalogPath) {
		doc[kv.Key] = kv.Value
	}
	provider := map[string]any{}
	for _, kv := range providerKeys(baseURL, settings) {
		provider[kv.Key] = kv.Value
	}
	providers[providerID] = provider
	out, err := toml.Marshal(doc)
	if err != nil {
		return nil, fmt.Errorf("encode Codex config: %w", err)
	}
	return out, nil
}

// rootKeys is the ordered set of root keys the gateway owns. The order matches
// the §12.3 example so a freshly created config.toml reads like the spec.
func rootKeys(settings clientcatalog.Settings, catalogPath string) []tomledit.KV {
	return []tomledit.KV{
		{Key: "model_provider", Value: providerID},
		{Key: "model", Value: settings.Model()},
		{Key: "model_catalog_json", Value: catalogPath},
	}
}

// providerKeys is the ordered set of keys inside [model_providers.ai-gateway].
func providerKeys(baseURL string, settings clientcatalog.Settings) []tomledit.KV {
	return []tomledit.KV{
		{Key: "name", Value: providerDisplayName(settings)},
		{Key: "base_url", Value: baseURL + "/c/codex/v1"},
		{Key: "wire_api", Value: "responses"},
		{Key: "env_key", Value: PlaceholderEnvironment},
	}
}

func Check(data []byte, baseURL string, settings clientcatalog.Settings) (bool, error) {
	doc, err := parse(data)
	if err != nil {
		return false, err
	}
	p, ok := providerBlock(doc)
	if !ok {
		return false, nil
	}
	catalogPath, _ := doc["model_catalog_json"].(string)
	if catalogPath == "" {
		return false, nil
	}
	if doc["model_provider"] != providerID || doc["model"] != settings.Model() {
		return false, nil
	}
	for _, kv := range providerKeys(baseURL, settings) {
		if p[kv.Key] != kv.Value {
			return false, nil
		}
	}
	return CatalogMatches(catalogPath, settings)
}

// Managed reports whether ai-gateway owns this configuration, regardless of
// which model or catalog generation was written into it. The point transaction
// uses it to update a managed file in place instead of creating a second
// restore point over an already pointed configuration.
func Managed(data []byte, baseURL string) (bool, error) {
	doc, err := parse(data)
	if err != nil {
		return false, err
	}
	p, ok := providerBlock(doc)
	if !ok {
		return false, nil
	}
	return doc["model_provider"] == providerID && p["base_url"] == baseURL+"/c/codex/v1", nil
}

func providerBlock(doc map[string]any) (map[string]any, bool) {
	providers, ok := doc["model_providers"].(map[string]any)
	if !ok {
		return nil, false
	}
	p, ok := providers[providerID].(map[string]any)
	return p, ok
}

func parse(data []byte) (map[string]any, error) {
	doc := map[string]any{}
	if len(data) == 0 {
		return doc, nil
	}
	if err := toml.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("parse Codex config: %w", err)
	}
	return doc, nil
}

func object(parent map[string]any, key string) (map[string]any, error) {
	if current, ok := parent[key]; ok {
		if current == nil {
			out := map[string]any{}
			parent[key] = out
			return out, nil
		}
		out, ok := current.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("Codex config field %q must be a table", key)
		}
		return out, nil
	}
	out := map[string]any{}
	parent[key] = out
	return out, nil
}
